<a href="https://colab.research.google.com/github/AransDino/AransDino/blob/main/clasificacionfaseinicialbenjamin.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (2.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2023.4)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2024.1)
Requirement already satisfied: numpy>=1.21.0 in /usr/local/lib/python3.10/dist-packages (from pandas) (1.25.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [ ]:
from google.colab import files

uploaded = files.upload()

Saving ClasificacionBenjamin.json to ClasificacionBenjamin.json

Programado por Ayoze Benitez


```
# funciones de ejemplo para demo

```
# Expandir codigo
```


```

In [20]:
import json

def obtener_equipo_primera_posicion(ruta_archivo):
    # Cargar el archivo JSON con la codificación correcta
    with open(ruta_archivo, 'r', encoding='ISO-8859-1') as archivo:
        datos = json.load(archivo)

    # Buscar el equipo en la primera posición
    for equipo in datos["teams"]:
        if equipo["Puesto"] == "1º":
            return equipo["Equipo"]

    return None

# Asegúrate de usar el nombre correcto del archivo que subiste
ruta_archivo = "ClasificacionBenjamin.json"
equipo_primera_posicion = obtener_equipo_primera_posicion(ruta_archivo)
print(f"El equipo en la primera posición es: {equipo_primera_posicion}")

El equipo en la primera posición es: D. CORUNA

In [22]:
import json
import pandas as pd

def mostrar_clasificacion_general(ruta_archivo):
    # Cargar el archivo JSON con la codificación correcta
    with open(ruta_archivo, 'r', encoding='ISO-8859-1') as archivo:
        datos = json.load(archivo)

    # Crear un DataFrame de pandas con los datos
    df = pd.DataFrame(datos["teams"])

    # Mostrar el DataFrame en formato de tabla
    return df

# Asegúrate de usar el nombre correcto del archivo que subiste
ruta_archivo = "ClasificacionBenjamin.json"
clasificacion_general = mostrar_clasificacion_general(ruta_archivo)
clasificacion_general

,Puesto,Equipo,PUNTOS,G-A FAVOR,G-ENCONTRA,DIF-GOLES,T-AMARILLA,T.ROJA
0,1º,D. CORUNA,15,19,8,11,3,1
1,2º,HARIA,13,17,6,11,3,5
2,3º,Inter Milan,13,13,3,10,1,2
3,4º,GRANADA,12,18,10,8,4,5
4,5º,Chelsea,12,14,7,7,1,1
5,6º,Fenerbahçe,12,14,8,6,3,3
6,7º,Z. Saint Petersburg,11,19,12,7,3,3
7,8º,O.Maritima,10,15,8,7,3,2
8,9º,Manchester United,10,11,6,5,0,3
9,10º,Rangers,9,17,13,4,1,4
10,11º,Celtic,9,10,8,2,3,3
11,12º,Napoli,8,14,6,8,4,2
12,13º,Ajax,8,15,13,2,3,2
13,14º,Bayer Leverkusen,8,8,6,2,3,3
14,15º,Bayern Munich,7,12,9,3,2,3
15,16º,Sporting CP,7,10,9,1,3,2
16,17º,Sevilla,7,15,15,0,3,2
17,18º,AC Milan,7,8,9,-1,3,1
18,19º,Tottenham,7,10,11,-1,3,2
19,20º,Villareal,7,11,12,-1,3,5
20,21º,Haria C.F,7,8,11,-3,2,3
21,22º,Real Madrid,7,12,16,-4,3,1
22,23º,SPORTING LISBOA,6,15,14,1,3,2
23,24º,Barcelona,6,15,15,0,3,3
24,25º,Atlético de Madrid,6,11,12,-1,1,4
25,26º,U.D Las Palmas,6,11,13,-2,1,1
26,27º,Arsenal,6,9,11,-2,2,2
27,28º,B Dortmund,6,10,16,-6,2,2
28,29º,Tottenham,5,6,5,1,3,2
29,30º,OSASUNA,5,15,17,-2,2,2
30,31º,Galatasaray,5,12,15,-3,4,2
31,32º,Liverpool,5,7,10,-3,2,4
32,33º,Juventus,5,8,13,-5,3,1
33,34º,PSV Eindhoven,4,12,18,-6,3,1
34,35º,BRITONG,4,7,13,-6,2,4
35,36º,UD. GUADALAJARA,4,8,18,-10,0,1
36,37º,Olympiacos,3,10,13,-3,3,2
37,38º,ALMERIA,3,8,12,-4,4,3
38,39º,Feyenoord,3,8,14,-6,2,3
39,40º,Manchester City,3,7,16,-9,3,1
40,41º,CSKA Moscow,2,12,16,-4,3,3
41,42º,Roma,0,5,19,-14,2,3

# Instalacion dependencias

In [23]:
!pip install pandas

In [ ]:
from google.colab import files

uploaded = files.upload()

# Preguntas sueltas

In [28]:
import json

def obtener_equipo_primera_posicion(ruta_archivo):
    # Cargar el archivo JSON con la codificación correcta
    with open(ruta_archivo, 'r', encoding='ISO-8859-1') as archivo:
        datos = json.load(archivo)

    # Buscar el equipo en la primera posición
    for equipo in datos["teams"]:
        if equipo["Puesto"] == "1º":
            return equipo["Equipo"]

    return None

# Asegúrate de usar el nombre correcto del archivo que subiste
ruta_archivo = "ClasificacionBenjamin.json"
equipo_primera_posicion = obtener_equipo_primera_posicion(ruta_archivo)
print(f"El equipo en la primera posición es: {equipo_primera_posicion}")

El equipo en la primera posición es: D. CORUNA

In [27]:
import json

def obtener_ultimos_diez_equipos(ruta_archivo):
    # Cargar el archivo JSON con la codificación correcta
    with open(ruta_archivo, 'r', encoding='ISO-8859-1') as archivo:
        datos = json.load(archivo)

    # Ordenar los equipos por su posición
    equipos_ordenados = sorted(datos["teams"], key=lambda x: int(x["Puesto"][:-1]))

    # Obtener los últimos diez equipos
    ultimos_diez_equipos = equipos_ordenados[-10:]

    return ultimos_diez_equipos

# Asegúrate de usar el nombre correcto del archivo que subiste
ruta_archivo = "ClasificacionBenjamin.json"
ultimos_diez_equipos = obtener_ultimos_diez_equipos(ruta_archivo)

# Imprimir los últimos diez equipos con sus posiciones
print("Los últimos diez equipos clasificados y que por tanto juegan la fase plata en la categoria benjamin son:")
for equipo in ultimos_diez_equipos:
    print(f'{equipo["Puesto"]}: {equipo["Equipo"]}')

Los últimos diez equipos clasificados y que por tanto juegan la fase plata en la categoria benjamin son:
33º: Juventus
34º: PSV Eindhoven
35º: BRITONG
36º: UD. GUADALAJARA
37º: Olympiacos
38º: ALMERIA
39º: Feyenoord
40º: Manchester City
41º: CSKA Moscow
42º: Roma

# Clasificacion general Equipos Benjamines a Color

In [25]:
import json
import pandas as pd

def mostrar_clasificacion_con_estilos(ruta_archivo):
    # Cargar el archivo JSON con la codificación correcta
    with open(ruta_archivo, 'r', encoding='ISO-8859-1') as archivo:
        datos = json.load(archivo)

    # Crear un DataFrame de pandas con los datos
    df = pd.DataFrame(datos["teams"])

    # Función para aplicar estilos de color a las filas
    def aplicar_estilo(fila):
        puesto = int(fila["Puesto"][:-1])
        if puesto <= 7:
            if puesto % 2 == 0:
                color = 'background-color: lightgreen'
            else:
                color = 'background-color: palegreen'
        elif 8 <= puesto <= 32:
            if puesto % 2 == 0:
                color = 'background-color: lightyellow'
            else:
                color = 'background-color: lemonchiffon'
        elif 33 <= puesto <= 42:
            if puesto % 2 == 0:
                color = 'background-color: lightgrey'
            else:
                color = 'background-color: gainsboro'
        else:
            color = ''
        return [color] * len(fila)

    # Aplicar los estilos de color
    df_estilizado = df.style.apply(aplicar_estilo, axis=1)

    return df_estilizado

# Asegúrate de usar el nombre correcto del archivo que subiste
ruta_archivo = "ClasificacionBenjamin.json"
clasificacion_estilizada = mostrar_clasificacion_con_estilos(ruta_archivo)
clasificacion_estilizada

# Clasificacion General Equipos Benjamines Primera Fase

In [26]:


# Asegúrate de usar el nombre correcto del archivo que subiste
ruta_archivo = "ClasificacionBenjamin.json"
clasificacion_estilizada = mostrar_clasificacion_con_estilos(ruta_archivo)
clasificacion_estilizada

import json
import pandas as pd

def mostrar_clasificacion_general(ruta_archivo):
    # Cargar el archivo JSON con la codificación correcta
    with open(ruta_archivo, 'r', encoding='ISO-8859-1') as archivo:
        datos = json.load(archivo)

    # Crear un DataFrame de pandas con los datos
    df = pd.DataFrame(datos["teams"])

    # Mostrar el DataFrame en formato de tabla
    return df

# Asegúrate de usar el nombre correcto del archivo que subiste
ruta_archivo = "ClasificacionBenjamin.json"
clasificacion_general = mostrar_clasificacion_general(ruta_archivo)
clasificacion_general

,Puesto,Equipo,PUNTOS,G-A FAVOR,G-ENCONTRA,DIF-GOLES,T-AMARILLA,T.ROJA
0,1º,D. CORUNA,15,19,8,11,3,1
1,2º,HARIA,13,17,6,11,3,5
2,3º,Inter Milan,13,13,3,10,1,2
3,4º,GRANADA,12,18,10,8,4,5
4,5º,Chelsea,12,14,7,7,1,1
5,6º,Fenerbahçe,12,14,8,6,3,3
6,7º,Z. Saint Petersburg,11,19,12,7,3,3
7,8º,O.Maritima,10,15,8,7,3,2
8,9º,Manchester United,10,11,6,5,0,3
9,10º,Rangers,9,17,13,4,1,4
10,11º,Celtic,9,10,8,2,3,3
11,12º,Napoli,8,14,6,8,4,2
12,13º,Ajax,8,15,13,2,3,2
13,14º,Bayer Leverkusen,8,8,6,2,3,3
14,15º,Bayern Munich,7,12,9,3,2,3
15,16º,Sporting CP,7,10,9,1,3,2
16,17º,Sevilla,7,15,15,0,3,2
17,18º,AC Milan,7,8,9,-1,3,1
18,19º,Tottenham,7,10,11,-1,3,2
19,20º,Villareal,7,11,12,-1,3,5
20,21º,Haria C.F,7,8,11,-3,2,3
21,22º,Real Madrid,7,12,16,-4,3,1
22,23º,SPORTING LISBOA,6,15,14,1,3,2
23,24º,Barcelona,6,15,15,0,3,3
24,25º,Atlético de Madrid,6,11,12,-1,1,4
25,26º,U.D Las Palmas,6,11,13,-2,1,1
26,27º,Arsenal,6,9,11,-2,2,2
27,28º,B Dortmund,6,10,16,-6,2,2
28,29º,Tottenham,5,6,5,1,3,2
29,30º,OSASUNA,5,15,17,-2,2,2
30,31º,Galatasaray,5,12,15,-3,4,2
31,32º,Liverpool,5,7,10,-3,2,4
32,33º,Juventus,5,8,13,-5,3,1
33,34º,PSV Eindhoven,4,12,18,-6,3,1
34,35º,BRITONG,4,7,13,-6,2,4
35,36º,UD. GUADALAJARA,4,8,18,-10,0,1
36,37º,Olympiacos,3,10,13,-3,3,2
37,38º,ALMERIA,3,8,12,-4,4,3
38,39º,Feyenoord,3,8,14,-6,2,3
39,40º,Manchester City,3,7,16,-9,3,1
40,41º,CSKA Moscow,2,12,16,-4,3,3
41,42º,Roma,0,5,19,-14,2,3